# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haM9bPyN6wJFQY1USvA3bqCUA0nN4Qrd

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""

import streamlit as st

st.set_page_config(
    page_title="Lista de Exercícios 4"
)

st.header("Projeto Final – Análise Contábil com Ajuste Econômico")

st.write(
    "Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit."
)

"""2) Importe os dados do arquivo empresas_dados.csv utilizando pandas e apresente todas as linhas da df (peso: 1,0)

Dica: Utilize `head(len(df))`
"""

import pandas as pd
df = pd.read_csv("empresas_dados.csv", sep=";")

st.dataframe(df.head(len(df)))

"""
3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

import matplotlib.pyplot as plt
df["Margem Líquida"] = df["Lucro Líquido"] / df["Receita Líquida"] * 100
df["ROA"] = df["Lucro Líquido"] / df["Ativo Total"] * 100

st.subheader("Indicadores: Margem Líquida e ROA por Ano")
fig, ax = plt.subplots()
df_grouped = df.groupby("Ano")[["Margem Líquida", "ROA"]].mean()
df_grouped.plot(kind="line", marker="o", ax=ax)
plt.title("Margem Líquida e ROA (Média por Ano)")
plt.ylabel("Percentual (%)")
plt.grid(True)
st.pyplot(fig)

"""
4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""

ipca = ipeadata.get_series("PRECOS12_IPCA12")

ipca = ipca[(ipca["YEAR"] >= 2010) & (ipca["YEAR"] <= 2024)]

ipca = ipca[["YEAR", "VALUE"]].drop_duplicates()
ipca = ipca.rename(columns={"YEAR": "Ano", "VALUE": "IPCA"})

st.subheader("IPCA Anual (2010-2024)")
st.dataframe(ipca)

"""
5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

df_completo = pd.merge(df, ipca, on="Ano", how="left")

df_completo["Receita Real"] = df_completo["Receita Líquida"] - (
    df_completo["Receita Líquida"] * (df_completo["IPCA"] / 100)
)

st.subheader("Dados Combinados com Receita Real")
st.dataframe(df_completo)

"""
6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

df_receitas = df_completo.groupby("Ano")[["Receita Líquida", "Receita Real"]].mean()

st.subheader("Receita Líquida vs Receita Real")
fig2, ax2 = plt.subplots()
df_receitas.plot(kind="line", marker="o", ax=ax2)
plt.title("Receita Líquida x Receita Real (média por ano)")
plt.ylabel("Valor em Reais")
plt.grid(True)
st.pyplot(fig2)

"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""

